Refined cvpi_test.sh, bin2channels channels2bin. They now work with dash. Current tests are passing.

diff --git a/tests/bin2channels b/tests/bin2channels
--- a/tests/bin2channels
+++ b/tests/bin2channels
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/bin/dash
+# -*- eval: (sh-set-shell "posix") -*-
 
 # bin2channels pixel_width image_width input_image outfile...
 
@@ -18,6 +19,8 @@
 # similarly for any more files.
 
 script_dir=$(dirname $0)
+interactive=0
+gnu=0
 
 if [ $# -lt 4 ]
 then
@@ -25,10 +28,26 @@ then
     exit 1;
 fi
 
+while getopts :ig OPT; do
+    case $OPT in
+	i|+i)
+	    interactive=1
+	    ;;
+	g|+g)
+	    gnu=1
+	    ;;
+	*)
+	    echo "usage: `basename $0` [+-ig} [--] ARGS..."
+	    exit 2
+    esac
+done
+shift $(( OPTIND - 1 ))
+OPTIND=1
+
 pixel_width=$1
 shift
 
-if [ -z $(printf "%d" $pixel_width | grep -e '^[1-9]\d*$') ]
+if [ -z $(printf "%d" $pixel_width | grep -e '^[1-9][0-9]*$') ]
 then
     printf "Pixel width, %d, must be a decimal number.\n" $pixel_width > /dev/stderr
     exit 1
@@ -37,7 +56,7 @@ fi
 image_width=$1
 shift
 
-if [ -z $(printf "%d" $image_width | grep -e '^[1-9]\d*$') ]
+if [ -z $(printf "%d" $image_width | grep -e '^[1-9][0-9]*$') ]
 then
     printf "Image width, %d, must be a decimal number.\n" $image_width > /dev/stderr
     exit 1
@@ -52,13 +71,53 @@ then
     exit 1;
 fi
 
+for file in $@
+do
+    if ! [ -f $file ] && [ -w $file ]
+    then
+	printf "%s exists, but is not a writable file\n" $file > /dev/stderr
+	exit 1;
+    else
+	if [ $interactive -eq 1 ]
+	then
+	    printf "%s exists, overwrite? [Y/N]: " $file
+	    while read -r response
+	    do
+		case $response in
+		    y|Y)
+			break
+			;;
+		    n|N)
+			echo "Aborting" > /dev/stderr
+			exit 1
+			;;
+		    *)
+			printf "Invalid reponse %s. Overwite? [Y/N]: " $response
+			;;
+		esac
+	    done
+	fi
+    fi
+done
+
 to_split=`mktemp`
+trap "rm -f $to_split" EXIT INT TERM
 
-# sed: remove the address column from od's output and remove blank lines, then turn it into a single line, then break at width
-od -v -t u1 $image | sed 's/^[[:digit:]]*[[:space:]]*\(\.*\)/\1/g' | sed '/^\s*$/d' | sed ':n;N;s/\n/ /; $!{b n}' | sed "s/\\(\\([[:digit:]]*[[:space:]]*\\)\\{$image_width\\}\\)/\\1\\n/g" > $to_split
+width=$(($image_width * $pixel_width))
 
-for start in $(seq 1 $#)
+if [ $gnu -eq 1 ]
+then
+    od -An -v -t x1 -w$width $image > $to_split
+else
+    # sed: turn od's output into a single line, then break at image_width * pixel_width
+    od -An -v -t x1 $image | sed ':n;N;s/\n/ /; $!{b n}' | sed "s/[[:space:]]*\\(\\([0-9a-fA-F]*[[:space:]]*\\)\\{$width\\}\\)/\\1\\n/g" > $to_split
+fi
+start=1
+while [ $start -le $# ]
 do
     # the first outfile will get data starting from the fist column; the second, data starting from the second column
     awk -f $script_dir/splitChannels.awk -v start="$start" -v jump="$pixel_width" $to_split > $(echo $@ | awk -v val="$start" '{print $val}')
+    start=$(($start + 1))
 done
+
+exit 0
diff --git a/tests/channels2bin b/tests/channels2bin
--- a/tests/channels2bin
+++ b/tests/channels2bin
@@ -1,14 +1,44 @@
-#!/bin/sh
+#!/bin/dash
+# -*- eval: (sh-set-shell "posix") -*-
 
-# channels2bin output_file channel_file_1 [channel_file_2 [channel_file_3 [channel_file_4]]]
+# channels2bin [-i] output_file channel_file...
+
+# channels2bin takes one or more input text files consisting of
+# tabular data and a file name to output binary data.
 
 script_dir=$(dirname $0)
+interactive=0
+
+close_fds() {
+    i=3
+    for file in $@
+    do
+	eval exec "$i<&-"
+	i=$(($i + 1))
+    done
+}
 
 if [ $# -lt 2 ]
 then
-    echo "Too few arguments";
+    echo "Too few arguments" > /dev/stderr;
     exit 1;
 fi
+
+while getopts :ic OPT; do
+    case $OPT in
+	i|+i)
+	    interactive=1
+	    ;;
+	c|+c)
+	    check_dims=1
+	    ;;
+	*)
+	    echo "usage: `basename $0` [+-ci} [--] ARGS..."
+	    exit 2
+    esac
+done
+shift $(( OPTIND - 1 ))
+OPTIND=1
 
 output_file=$1
 shift
@@ -19,8 +49,26 @@ then
     then
 	printf "%s exists, but is not a writable file\n" $output_file > /dev/stderr
 	exit 1;
-    #else
-	# TODO ask Y/N question if -i option is set
+    else
+	if [ $interactive -eq 1 ]
+	then
+	    printf "%s exists, overwrite? [Y/N]: " $output_file
+	    while read -r response
+	    do
+		case $response in
+		    y|Y)
+			break
+			;;
+		    n|N)
+			echo "Aborting" > /dev/stderr
+			exit 1
+			;;
+		    *)
+			printf "Invalid reponse %s. Overwite? [Y/N]: " $response
+			;;
+		esac
+	    done
+	fi
     fi
 fi
 
@@ -33,74 +81,91 @@ do
     fi
 done
 
-channel_file_1=$1
-shift
+field_num=$(awk 'NR == 1 { print NF; exit }' $1)
+record_num=$(grep -c -v -e '^[[:space:]]*$' $1)
 
-channel_file_1_full=$(readlink -f $channel_file_1)
-
-channel_file_1_filtered=`mktemp`
-chmod g+r $channel_file_1_filtered
-
-# can't remove last line feed from files and files may or maynot have one, so add one using `echo'
-echo $(cat $channel_file_1_full) | sed '/^\s*$/d' > $channel_file_1_filtered
-
-awk_opts=
-if [ $# -ne 0 ]
+# often the last line is blank, ignore it
+if [ ${#check_dims} -ne 0 ]
 then
-    channel_file_2=$1
-    shift
-    channel_file_2_full=$(readlink -f $channel_file_2)
-
-    channel_file_2_filtered=`mktemp`
-    chmod g+r $channel_file_2_filtered
-
-    echo $(cat $channel_file_2_full) | sed '/^\s*$/d' > $channel_file_2_filtered
-    
-    awk_opts=" -v g_file='$channel_file_2_filtered'"
-fi
-
-if [ $# -ne 0 ]
-then
-    channel_file_3=$1
-    shift
-    channel_file_3_full=$(readlink -f $channel_file_3)
-
-    channel_file_3_filtered=`mktemp`
-    chmod g+r $channel_file_3_filtered
-
-    echo $(cat $channel_file_3_full) | sed '/^\s*$/d' > $channel_file_3_filtered
-
-    awk_opts="$awk_opts -v b_file='$channel_file_3_filtered'"
-fi
-
-if [ $# -ne 0 ]
-then
-    channel_file_4=$1
-    shift
-    channel_file_4_full=$(readlink -f $channel_file_4)
-
-    channel_file_4_filtered=`mktemp`
-    chmod g+r $channel_file_4_filtered
-
-    echo $(cat $channel_file_4_full) | sed '/^\s*$/d' > $channel_file_4_filtered
-    
-    awk_opts="$awk_opts -v a_file='$channel_file_4_filtered'"
-fi
-
-# TODO store output to a file, output could exceed max variable size
-one_line=$(awk -f $script_dir/channelFilesCombine.awk $awk_opts $channel_file_1_filtered)
-exit_code=$?
-if test $exit_code -eq 0
-then
-
-    itter=0
-    for data in $one_line
+    # check that all of the files are the same dimension
+    for file in $@
     do
-	dd if=$script_dir/dd_lookup_table of=$output_file bs=1 skip=$data count=1 seek=$itter > /dev/null 2> /dev/null
-	itter=$(($itter + 1))
+	rn=$(grep -c -v -e '^[[:space:]]*$' $file)
+
+	if [ $rn -ne $record_num ]
+	then
+	    printf "%s and %s have mismatched number of lines\n" $1 $file > /dev/stderr
+	    exit 1
+	fi
+
+	i=1
+	while [ $i -le $rn ]
+	do
+	    fn=$(grep -v -e '^[[:space:]]*$' $file | awk "NR == $i { print NF; exit}")
+	    if [ $fn -ne $field_num ]
+	    then
+		printf "%s and %s have mismatched number of fields %d and %s\n" $1 $file $field_num $fn > /dev/stderr
+		exit 1
+	    fi
+	    i=$(($i + 1))
+	done
     done
-	     
-else
-    echo "AWK returned an error" > /dev/stderr
-    exit 1
 fi
+
+#echo "inputs: $@" > /dev/stderr
+trap "close_fds" EXIT INT TERM
+i=3
+for file in $@
+do
+    eval exec "$i< $file"
+    i=$(($i + 1))
+done
+
+instruction_list=`mktemp`
+trap "rm -f $instruction_list" EXIT INT TERM
+
+output_file_full=$(readlink -f $output_file)
+dd_lookup_table=$(readlink -f $script_dir/dd_lookup_table)
+
+i=1
+IFS=''				# read an entire line
+while [ $i -le $record_num ]
+do
+    k=3
+    channel=0
+    for file in $@
+    do
+
+	#echo "k $k" > /dev/stderr
+	eval read -r "<&$k line"
+	k=$(($k + 1))
+
+	#echo "line $line" > /dev/stderr
+
+	j=1
+	while [ $j -le $field_num ]
+	do
+	    data=$(printf "%d" $(printf "0x%s" $(echo $line | awk "{ print \$$j }")))
+	    #echo "data:" $data > /dev/stderr
+
+	    seek=$(($(($i-1)) * $field_num * $# + $(($j-1)) * $# + $channel))
+	    #printf "i: %d\nrecord_num: %d\nj: %d\nfield_num: %d\nchannel: %d\nchannels %d\nseek: %d\n" $i $record_num $j $field_num $channel $# $seek > /dev/stderr
+	    echo "$seek dd if=$dd_lookup_table of=$output_file_full bs=1 skip=$data count=1 seek=$seek > /dev/null 2> /dev/null" >> $instruction_list
+	    j=$(($j + 1))
+	done
+	channel=$(($channel + 1))
+    done
+    i=$(($i + 1))
+
+    # dd has to insert bytes into the output in order; it cannot jump
+    # around; data is out of order due to channels being processed
+    # before pixel columns, but this way the the program is reading an
+    # entire input line at a time and saving the location for the next read
+    sort -n $instruction_list | cut -d " " -f 2- | while read -r instruction
+    do
+	eval "$instruction"
+    done
+    # clear the file
+    cat /dev/null > $instruction_list    
+done
+exit 0
